### ISSUE TITLE
History view cuts of the start of all queries, if one of the queries is longer than the tool width

### ISSUE THREAD

**Issue by damevski** [vcu-swim-lab/stack-intheflow#116]
![sitf_1](https://user-images.githubusercontent.com/3277136/28970464-a3d42b90-78f6-11e7-9ef2-18e173dfd543.PNG)

**Comment by cptcomo** [comment]
Fixed in #118 
![116](https://user-images.githubusercontent.com/9583117/28975364-b8074f14-7907-11e7-979c-149917afff4c.png)
