### ISSUE TITLE
Plugin window doesn't appear

### ISSUE THREAD

**Issue by cooglejj** [vcu-swim-lab/stack-intheflow#15]
As of commit fffea8cfe21ce78595c56062031b800e932ac8b4 I'm experiencing the same issue that Jeet's talked about: The plugin window doesn't show up when the project is run.

**Comment by Zerthick** [comment]
I've cloned the repo onto my other (Windows 10) PC and after setting the project SDK to my local Intellij Install and setting the run configuration to use it as the jre, everything is working and the tool window is visible.
![projectstructure](https://cloud.githubusercontent.com/assets/6935134/19293771/16a5c0fc-8ff5-11e6-80e0-482a9397ea19.PNG)
![runconfig](https://cloud.githubusercontent.com/assets/6935134/19293774/1aa716e2-8ff5-11e6-8c79-4ffcd2d3484d.PNG)

I'm not sure what could be leading to the issue, but one thing you can try is going to View > Tool Windows and seeing if you can select StackInTheFlow to be visible.

**Comment by cooglejj** [comment]
Interesting. I did a fresh clone of the repository (on Ubuntu 16.04) and mirrored your settings and I'm still getting nothing. Here's screenshots.
![screenshot from 2016-10-12 09-53-31](https://cloud.githubusercontent.com/assets/14185019/19313110/57b6a264-9063-11e6-9cb6-ea7603335e5d.png)
![screenshot from 2016-10-12 09-52-23](https://cloud.githubusercontent.com/assets/14185019/19313114/5c4a7828-9063-11e6-88a9-ec2068b9ef84.png)
![screenshot from 2016-10-12 09-52-09](https://cloud.githubusercontent.com/assets/14185019/19313117/5fb307fa-9063-11e6-86a4-14d0cd3ae21c.png)
It's strange that it's working on your machine, but not on my machine, I'm really not sure what the issue is.

**Comment by damevski** [comment]
It wasn't working for me either, but I got it to work by messing around with this. Now it seems to react well to any changes I make to the plugin.

http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/deploying_plugin.html

Not sure if that helps.

**Comment by cooglejj** [comment]
That works for me as well. It's not ideal, but it gets the job done.

**Comment by jeetgajjar** [comment]
Issues and solution:
**This is running a clean version of the project**

I tried following the link Dr. Damevski provided. 
Issue: when cloning project, src isn't made of "Source" (blue folder) and thus I couldn't "Prepare module for Deployment." 
I was able to follow the instructions and now have our plugin displaying on my native IntelliJ instance.
