### ISSUE TITLE
investigate how to extract the code from the current editor window

### ISSUE THREAD

**Issue by damevski** [vcu-swim-lab/stack-intheflow#26]

**Comment by Zerthick** [comment]
This can easily be done, relevant docs: http://www.jetbrains.org/intellij/sdk/docs/tutorials/editor_basics/working_with_text.html

**Comment by damevski** [comment]
This is done. Needs to be implemented

**Comment by jeetgajjar** [comment]
This plugin collects data on completion: 
https://github.com/JetBrains/intellij-stats-collector/
