### ISSUE TITLE
create a UI sketch of how we want the UI to look like

### ISSUE THREAD

**Issue by damevski** [vcu-swim-lab/stack-intheflow#27]

**Comment by Zerthick** [comment]
We may want to model our UI on the existing stackoverflow search UI http://stackoverflow.com/search?q=Hello+World

**Comment by jeetgajjar** [comment]
I agree, Chase. However, lets still come up with some rough sketches on how we want lay everything out- click title then drop down Body, tabs for sorting, pagination, etc...
Lets be as detailed as possible while keeping the overall goal in mind- making this plugin useful and user-friendly.

**Comment by jeetgajjar** [comment]
![wireframe-plugingajjar](https://cloud.githubusercontent.com/assets/10531767/20931960/edfa1306-bba0-11e6-98c1-7cc22cdac909.png)

**Comment by jeetgajjar** [comment]
![wireframepart2](https://cloud.githubusercontent.com/assets/10531767/21144415/84db4c6e-c118-11e6-8ad5-bdbcd4e3d4ec.png)
![wireframepart1](https://cloud.githubusercontent.com/assets/10531767/21144416/84e0bf46-c118-11e6-902d-3e0dd4ef9a4a.png)
