### ISSUE TITLE
create an icon for the app

### ISSUE THREAD

**Issue by damevski** [vcu-swim-lab/stack-intheflow#29]

**Comment by jeetgajjar** [comment]
John's design:
![john_icon](https://cloud.githubusercontent.com/assets/10531767/21143445/c6b211a8-c114-11e6-839b-85a359da1de7.png)

**Comment by jeetgajjar** [comment]
![icon2](https://cloud.githubusercontent.com/assets/10531767/21151679/5eb5c4d8-c131-11e6-899f-ee06605ce1aa.JPG)
![icon3](https://cloud.githubusercontent.com/assets/10531767/21151680/6163de04-c131-11e6-93ac-79a71c5ec9fc.JPG)
![icon1](https://cloud.githubusercontent.com/assets/10531767/21151685/64787e88-c131-11e6-911b-c9da1dc92854.JPG)
More icons to come

Click on the icon to see the full image; GitHub posted them sideways as a preview

**Comment by jeetgajjar** [comment]
Here is an updated icon. 
.JPG:
![stackoverflowfinal](https://cloud.githubusercontent.com/assets/10531767/22490279/59404df4-e7ea-11e6-8230-69214f0b6a1d.jpg)

.PNG:
![stackoverflowfinal](https://cloud.githubusercontent.com/assets/10531767/22490285/5ff31b7c-e7ea-11e6-8c06-db837b9c4841.png)
