### ISSUE TITLE
Searching on the stackoverflow website returns results that our plugin does not.

### ISSUE THREAD

**Issue by cooglejj** [vcu-swim-lab/stack-intheflow#41]
For example, searching for "HTMLEditorKit insert blank line" gets 1 result in stackoverflow, and no results in our plugin. This may or may not be a real problem, but it might be worth investigating.

Also a point of interest is doing the same search on google returns multiple stackoverflow results that are not found by stackoverflow itself.

**Comment by damevski** [comment]
It's a problem. Nothing we can do about it.
