### ISSUE TITLE
fork and replace jlist with an html list

### ISSUE THREAD

**Issue by damevski** [vcu-swim-lab/stack-intheflow#63]

**Comment by damevski** [comment]
incorporate javascript?

**Comment by Zerthick** [comment]
This seems relevant: https://stackoverflow.com/questions/2438201/pure-java-html-viewer-renderer-for-use-in-a-scrollable-pane JavaFX webview, also supports javascript

**Comment by Zerthick** [comment]
Created new branch to handle this feature [feature/htmlUI](/vcu-swim-lab/stack-intheflow/tree/feature/htmlUI)

**Comment by Zerthick** [comment]
Implemented by @cptcomo
