### ISSUE TITLE
Creating a new UI

### ISSUE THREAD

**Issue by cptcomo** [vcu-swim-lab/stack-intheflow#84]
To replace the current UI, we are looking to use JavaFX's WebView and WebEngine classes to display the search and search results. 

The new UI should have all the basic features that the previous one had, including:
- Searching with manual queries
- Searching with automatic queries
- Error suggestions
- Titles and snippet of each search result

We are also looking to include clicking on tags to search by tag, and ordering search results based on search methods such as relevance, new, and most upvoted.

Steps to complete this task is to develop a concrete design for the new UI, learning the new tools in JavaFX, creating the UI, and testing. Input in the design for the new UI is greatly appreciated.

**Comment by cptcomo** [comment]
Elaborating a bit more on the requirements and our initial ideas:

Manual Query - Remaining mostly the same: search bar and button.

Auto Query Indication - Users will maintain the ability to right click and auto query. There won't be a feature in the UI to generate an auto query. This will just indicate that the plugin has automatically generated a query so that the user knows. We think that we will indicate this by showing an icon next to the search bar; hovering over it will reveal this information.

Error Suggestion - This is still a work in progress. We think that we should just automatically generate the error query for the user rather than letting the user click below the search bar. To remedy the potential problem that it may overwrite the user's query, we are looking to have multiple tabs open for searching, so just open a new tab.

Search Results - Will likely remain very similar. Search titles and excerpts will remain similar. A possible new addition is to have something on the side indicating how many votes and how many answers the result has, because sometimes a question has no answer yet. We are not sure how valuable this feature is. Also something to consider is dynamically resizing the search result boxes to minimize wasted white space and allow for dynamic sizing of search excerpts rather than a hard cap on characters.

Search Tags - At the bottom of each search result box will be related tags like StackOverflow. Clicking on the tag will add the tag to the search query. Tags searched will be in a gray(?) banner below the search box, holding all the tags being searched, where clicking on a tag there will remove it. The user can also use the tag syntax: [tag] in the search box. 

Search Methods - A dropdown. A concern with this is that search results are already being re-ordered based on the personalization. A possible solution is to only do our re-ordering when searching by relevance, and leave it alone for top, new, etc.


![brainstorm](https://user-images.githubusercontent.com/9583117/27546768-c0f0ee7e-5a61-11e7-8625-5a841b188ef6.jpeg)

**Comment by cptcomo** [comment]
The rough draft for the layout is similar to the old layout. It will allow for the new features such as showing the tags and the search methods, but no big changes.

![layoutideas](https://user-images.githubusercontent.com/9583117/27546846-fae145c0-5a61-11e7-9ba8-c49d7b5cf4fa.jpeg)

**Comment by cptcomo** [comment]
A few features that remain to be implemented in the next few weeks:

1. External Link to Question - Make the title a link to open in browser rather than double clicking - Pretty simple change

2. Error Trigger - Connect the new UI to the Error queries. We'll have the tool just automatically generate the query rather than having suggestions.

3. History (Tabs, Forward-backward) - To fix a potential problem of an autoquery overwriting a user's manual query, we want to have something for the user to retain the previous query. The idea that seems best is the history, similar to a browser. We'll just have a dropdown of the previous queries that were made. Refer to clock icon in picture.

4. Search methods - Instead of having a button dropdown, we'll just have a small dropdown in the search box. Refer to dropdown arrow in picture.

5. Autoquery Icon - Make an indication to the user that a query was autogenerated.

6. Adding/Removing Tags - Query each time this happens.

7. Favorites(?) - Have a favorites menu for user to save their favorite posts. A complicating factor is persisting favorites.

**Comment by cptcomo** [comment]
![file_000](https://user-images.githubusercontent.com/9583117/28470609-3787b374-6e08-11e7-8264-0b95f8e91851.jpeg)

**Comment by Zerthick** [comment]
Implemented by @cptcomo
